### ISSUE TITLE
Game logic

### ISSUE THREAD

**Issue by frontend-sensei** [frontend-sensei/web-games#9]
- [x] [Implement level class](https://github.com/frontend-sensei/web-games/issues/10)
- [x] [Implement game class](https://github.com/frontend-sensei/web-games/issues/11)
- [x] [Implement game timer class](https://github.com/frontend-sensei/web-games/issues/14)
- [x] [Implement game coordinates class](https://github.com/frontend-sensei/web-games/issues/15)
- [x] [Implement saving progress class](https://github.com/frontend-sensei/web-games/issues/12)

### Game process:
- [x] start game
- [x] start timer
- [x] start moving bar line
- [x] listen space press
- [x] on user press check coordinates

If not ok:
- [x]  decrease attempts 
- [x]  if attempts equals zero - game over

If ok:
- [x]  go to the next step
- [x]  after the last step, display "You won!" message and button "continue" in the popup 
- [x]  after the last step, save progress
- [x]  on click "back to home" redirect to the home page
- [x]  on click "continue" reload game page
